machine:
  services:
    - docker

dependencies:
  cache_directories:
    - ~/docker

deployment:
  production:
    branch: main
      commands:
          - docker build -t registry.heroku.com/$HEROKU_APP_NAME/web .
          - docker login --email=$HEROKU_LOGIN --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
          - docker push registry.heroku.com/$HEROKU_APP_NAME/web:latest 
